### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by 66246764** [Fangyin1994/KCL#10]
作者您好，我按照您提供的版本信息配置环境，并直接使用了你8.58G的pretrain数据，但是运行bash finetune是出现以下错误importerrror
![image](https://user-images.githubusercontent.com/54762477/209607379-acc52aa3-8e9b-411f-bfcc-03d24ca45459.png)

**Comment by 66246764** [comment]
我尝试了python3.7和3.8版本，都出现了这个问题

**Comment by 66246764** [comment]
我注意到kmpnn.py中。import fchdir这句话是灰色的
![image](https://user-images.githubusercontent.com/54762477/209609812-8789e142-f648-49d1-863e-3500440c769e.png)
所以我注释这句import后运行，又出现了新的错误，貌似并没有在您的readme中提到，请问这要如何解决呢？
![image](https://user-images.githubusercontent.com/54762477/209609893-5bc733bd-812f-4ab2-a62f-1bfd649be789.png)

**Comment by Fangyinfff** [comment]
您好，我们的代码是在linux上运行的，请您尽量迁移到linux上运行，否则后续可能会出现更多错误。

**Comment by 66246764** [comment]
好的谢谢
