### ISSUE TITLE
Ref: #5

### ISSUE THREAD

**Issue by dtchang** [Fangyin1994/KCL#6]
Status as of today:
Releases
No releases published

**Comment by Fangyinfff** [comment]
Hi, I'm not quite sure what you're trying to say, can't you see the code from https://github.com/ZJU-Fangyin/KCL/tree/main/code?

**Comment by dtchang** [comment]
I can see the code and access individual files. However, I can't find the zip file to download. (Github used to provide that.)

Here is an example of a project with published release(s):
Releases 4
v0.4.0 Latest

And when you click on that, you can find:
Assets 2
Source code (zip)
Source code (tar.gz)

**Comment by Fangyinfff** [comment]
![image](https://user-images.githubusercontent.com/61076726/163505383-b541ec88-bb44-4314-9988-fa9372bc865e.png)

**Comment by dtchang** [comment]
I had my browser zoom level set at 150% and was not able to see the buttons. I reduced it to 133% and was able to see them. Thanks.

**Comment by Fangyinfff** [comment]
Ok, no thanks.🤔
